# Generated by Django 2.1.2 on 2019-01-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181207_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='commentaire',
        ),
    ]
